apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: springmvc
  name: 'springmvc-{BUILD_NUMBER}'
spec:
  replicas: 1
  selector:
    matchLabels:
      run: springmvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: springmvc
    spec:
      containers:
      - image: wiprorepo/springmvc:latest
        name: 'springmvc-{BUILD_NUMBER}'
        ports:
        - containerPort: 8080
        resources: {}
status: {}
