apiVersion: v1
kind: Service
metadata:
  labels:
    run: service-name
  name: service-name
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: deployment-name
  sessionAffinity: None
  type: LoadBalancer