apiVersion: v1
kind: Service
metadata:
  labels:
    run: springmvc
  name: springmvc-service-${env.BUILD_NUMBER}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: springmvc-${env.BUILD_NUMBER}
  sessionAffinity: None
  type: LoadBalancer